In [17]:
import pandas as pd
import numpy as np
import os
import shutil

In [2]:
linkage_path = "../EntityLinking/data/artist_predictions.csv"
linkage_df = pd.read_csv(linkage_path, index_col=False)

artsy_path = "../Scrape/Artsy/Data/CleanedArtsyData.csv"
artsy_df = pd.read_csv(artsy_path)

ww_path = "../Scrape/Widewalls/data/CleanedWidewallsData.csv"
ww_df = pd.read_csv(ww_path)

artsy_name_path = "../Scrape/Artsy/Data/ArtsyArtist.csv"
artsy_name_df = pd.read_csv(artsy_name_path)

ins_path = "../InstagramFinder/data/ArtistWithIns.csv"
ins_df = pd.read_csv(ins_path)

In [3]:
ins_df = ins_df.drop(['Unnamed: 0','Artsy','Widewalls'],axis = 1)
ins_df

,artist_name,artist_website,artist_ins
0,Roy Lichtenstein,lichtensteinfoundation.org,https://www.instagram.com/roylichtenstein/?hl=en
1,Josep Guinovart,NaN,NaN
2,Macha Poynder,www.machapoynder.com,https://www.instagram.com/macha_poynder/?hl=en
3,Eddie Martinez,eddiemartinez.net,https://www.instagram.com/_eddiemartinez/?hl=en
4,Louis Masai,louismasai.com,https://www.instagram.com/louismasai/?hl=en
...,...,...,...
495,Jaume Plensa,jaumeplensa.com,NaN
496,Chris Ofili,NaN,https://www.instagram.com/chrisofili/?hl=en
497,Douglas Gordon,www.gordondouglas.org,https://www.instagram.com/douglas_g_gordon/?hl=en
498,Georges Braque,www.georgesbraque.org,NaN
499,Ernst Haas,ernst-haas.com,NaN

In [4]:
ww_df

,artist_names,full_bios,id
0,Joan Miro,"The mind is a fascinating thing, and there’s n...",1
1,David Shrigley,David Shrigley is a Glasgow-based British arti...,2
2,Kyriakos Kaziras,Heavily influenced by painting and considering...,3
3,Salvador Dali,"One of the most original, innovative, and famo...",4
4,David Yarrow,An artist followed by an amazing reputation fo...,5
...,...,...,...
2529,Tadahiko Ikegaki,Tadahiko Ikegaki is a Japanese contemporary ar...,2530
2530,Charles Laib Bitton,Charles Laib Bitton is a Belgian contemporary ...,2531
2531,Derrick Adams,"Born in Baltimore, Derrick Adams is an America...",2532
2532,Alice Suret-Canale,Alice Suret-Canale is a French contemporary pa...,2533
2533,Tatiana Nega,"Drawing since early childhood, Tatiana Nega is...",2534

In [5]:
ww_df.columns = ["artist_name",'full_bio','id']
ww_df

,artist_name,full_bio,id
0,Joan Miro,"The mind is a fascinating thing, and there’s n...",1
1,David Shrigley,David Shrigley is a Glasgow-based British arti...,2
2,Kyriakos Kaziras,Heavily influenced by painting and considering...,3
3,Salvador Dali,"One of the most original, innovative, and famo...",4
4,David Yarrow,An artist followed by an amazing reputation fo...,5
...,...,...,...
2529,Tadahiko Ikegaki,Tadahiko Ikegaki is a Japanese contemporary ar...,2530
2530,Charles Laib Bitton,Charles Laib Bitton is a Belgian contemporary ...,2531
2531,Derrick Adams,"Born in Baltimore, Derrick Adams is an America...",2532
2532,Alice Suret-Canale,Alice Suret-Canale is a French contemporary pa...,2533
2533,Tatiana Nega,"Drawing since early childhood, Tatiana Nega is...",2534

In [6]:
linkage_list = []
for i in range(len(linkage_df)):
    linkage_list.append([linkage_df.iloc[i][0],linkage_df.iloc[i][1]])
artsy_list = [x[0] for x in linkage_list]
ww_list = [x[1] for x in linkage_list]

In [7]:
header = list(artsy_df.columns)
header.append('biography')
print(header)

['id', 'media', 'url', 'artist_name', 'artist_url', 'work_name', 'work_year', 'media_long', 'dimension', 'gallery_name', 'gallery_url', 'bid', 'price', 'img_url', 'biography']

In [8]:
artsy_name_df = artsy_name_df.loc[artsy_name_df['id'].isin(artsy_list)]
artist_list = list(artsy_name_df['artist_name'])
artsy_df = artsy_df.loc[artsy_df['artist_name'].isin(artist_list)]
ww_df = ww_df.loc[ww_df['artist_name'].isin(artist_list)]
ww_df = ww_df.drop(['id'], axis = 1)
ww_df

          artist_name                                           full_bio
1      David Shrigley  David Shrigley is a Glasgow-based British arti...
4        David Yarrow  An artist followed by an amazing reputation fo...
6     Dan Christensen  Dan Christensen was an American abstract paint...
10               KAWS  In the late ’80s and early ’90s, the interesti...
18        Andy Warhol  It was the beginning of the 1950s when the art...
...               ...                                                ...
2423  William Gropper  William Gropper was a versatile American artis...
2454    Zhoujie Zhang  Zhoujie Zhang is a Chinese furniture designer,...
2492  Francisca Sutil  Francisca Sutil is an award-winning Chilean co...
2510        Jiha Moon  Jiha Moon is a Korean artist whose paintings, ...
2531    Derrick Adams  Born in Baltimore, Derrick Adams is an America...

[500 rows x 2 columns]

In [9]:
artsy_df = artsy_df.merge(ww_df, on = "artist_name", how = 'left' )
artsy_df = artsy_df.merge(ins_df, on = "artist_name", how = 'left' )

In [10]:
artsy_df.to_csv('FinalDataSet.csv', index=False)

In [11]:
final_id = list(artsy_df['id'])

In [12]:
try:
    os.mkdir('images')
except:
    pass

In [13]:
def find(name, path):
    for root, dirs, files in os.walk(path):
        if name in files:
            return os.path.join(root, name)

In [14]:
#shutil.copyfile(src, dst)
img_file_path = "../Scrape/Artsy"
#print([x[1] for x in os.walk(img_file_path)])
img_folder_path = [x[2] for x in os.walk(img_file_path)]
img_path = []
for f in img_folder_path:
    img_path += f
final_img_path = []
for i in img_path:
    if i[:-4] in final_id:
        final_img_path.append(i)
print(len(final_img_path))
for  i in range(len(final_img_path)):
    final_img_path[i] = find(final_img_path[i],img_file_path)

2485

In [15]:
final_img_path[0]

'../Scrape/Artsy/Data/design/design1467.png'

In [16]:
for i in final_img_path:
    shutil.copyfile(i, "images/"+i.split('/')[-1])

In [30]:
class_path = "../DeepLearning/data/style_classification.csv"
class_df = pd.read_csv(class_path)
class_df = class_df.drop('Unnamed: 0',axis = 1)
class_df

                     id                 class
0            prints1293          contemporary
1             prints762  contemporary-realism
2             prints947  contemporary-realism
3     works-on-paper418          contemporary
4             prints348        conceptual-art
...                 ...                   ...
2477          design991        conceptual-art
2478          design592          contemporary
2479           design31  contemporary-realism
2480     mixed-media494          contemporary
2481    photography1347           neo-pop-art

[2482 rows x 2 columns]

In [32]:
final_path = "FinalDataset_with_all.csv"
final_df = pd.read_csv(final_path)
final_df = final_df.merge(class_df, on = "id", how = 'left')
try:
    final_df = final_df.drop("Unnamed: 0",axis = 1)
except:
    pass
final_df.to_csv('FinalDataset_with_all.csv', index=False)

In [33]:
final_df

,id,media,url,artist_name,artist_url,work_name,work_year,media_long,dimension,gallery_name,...,location,color1,color2,color3,color4,color_group1,color_group2,color_group3,color_group4,class
0,painting15,painting,https://www.artsy.net/artwork/hebru-brantley-d...,Hebru Brantley,https://www.artsy.net/artist/hebru-brantley,"Death Of The Black Fairy, The Great Debate Pt. 5",2020,Acrylic & Diamond Dust on Canvas,60 × 60 in | 152.4 × 152.4 cm,Corridor Contemporary,...,Chicago,#E7DFCC,#A69784,#403931,#877C76,682.0,850.0,37.0,772.0,post-minimalism
1,prints369,prints,https://www.artsy.net/artwork/hebru-brantley-f...,Hebru Brantley,https://www.artsy.net/artist/hebru-brantley,Flower N Word,2022,"22-color Hand-Pulled Screen Print, Saunders Wa...",40 × 30 in | 101.6 × 76.2 cm,Pinto Gallery,...,Chicago,#FFFFFF,#FCE44C,#65C94D,#2E3432,965.0,50.0,579.0,858.0,post-minimalism
2,prints826,prints,https://www.artsy.net/artwork/hebru-brantley-m...,Hebru Brantley,https://www.artsy.net/artist/hebru-brantley,Monoprint,2017,Hand-Pulled Screen Print on Mohawk Superfine U...,24 × 18 in | 61 × 45.7 cm,MODCLAIR,...,Chicago,#1F201B,#F4EDDB,#B1865C,#CBBBAB,128.0,570.0,656.0,580.0,street-art
3,photography133,photography,https://www.artsy.net/artwork/hebru-brantley-n...,Hebru Brantley,https://www.artsy.net/artist/hebru-brantley,Night Flight,2021,Digital print with screen printed glow in the ...,29 × 36 in | 73.7 × 91.4 cm,Heritage: Urban Art,...,Chicago,#161E21,#02855D,#1A5747,#6FBA9B,583.0,452.0,21.0,777.0,transavantgarde
4,painting37,painting,https://www.artsy.net/artwork/miaz-brothers-ma...,Miaz Brothers,https://www.artsy.net/artist/miaz-brothers,Maestro,2022,Acrylic on canvas,40 1/5 × 29 9/10 in | 102 × 76 cm,Maddox Gallery,...,Cyan,#181A15,#2F342E,#43492F,#B8A36C,942.0,350.0,970.0,759.0,minimalism
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2474,design1182,design,https://www.artsy.net/artwork/rivane-neuenschw...,Rivane Neuenschwander,https://www.artsy.net/artist/rivane-neuenschwa...,(Anonymous Furniture 2),2007,Wood,31 9/10 × 14 1/5 × 14 1/5 in | 81 × 36 × 36 cm,Fortes D'Aloia & Gabriel,...,Belo Horizonte,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,conceptual-art
2475,design1269,design,https://www.artsy.net/artwork/paola-pivi-universe,Paola Pivi,https://www.artsy.net/artist/paola-pivi,Universe,2021,Wool and bamboo silk,4/5 × 113 × 78 7/10 in | 2 × 287 × 200 cm,Paradisoterrestre,...,Milan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,minimalism
2476,design1278,design,https://www.artsy.net/artwork/calman-shemi-mod...,Calman Shemi,https://www.artsy.net/artist/calman-shemi,Modernist Israeli Soft Tapestry Wall Hanging R...,1989,"Mixed Media, Wool",71 × 45 in | 180.3 × 114.3 cm,Lions Gallery,...,Mendoza,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,contemporary-realism
2477,design1440,design,https://www.artsy.net/artwork/red-grooms-moons...,Red Grooms,https://www.artsy.net/artist/red-grooms,Moonstruck (Homage to Cher),1994,Porcelain 3D Plate. Artist Signature Fired int...,10 3/4 in diameter | 27.3 cm diameter,Alpha 137 Gallery,...,Nashville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,contemporary
2478,design1453,design,https://www.artsy.net/artwork/max-ingrand-floo...,Max Ingrand,https://www.artsy.net/artist/max-ingrand,Floor lamp,1955,"Glass, nickel-plated brass, painted brass, bra...",76 × 11 4/5 × 11 4/5 in | 193 × 30 × 30 cm,Gokelaere & Robinson,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,minimalism